### ISSUE TITLE
Error: success

### ISSUE THREAD

**Issue by hermanthe** [devryan/GamePanelX-V3#114]
Hi,
i got a pretty weird Error when i click Install (Master).... It says "Error: success" 

OS: Debian 7

Can anyone help?

http://imgur.com/9JEEUdP

UPDATE:

Got it, apache error log:

Undefined index: language in /var/www/gpx/install/install_actions.php on line 28

When i change the language, i got the "Error: success"-Error (changed it to German). If if don't change the language, it works

**Comment by devryan** [comment]
What browser?  Can you try the very latest 3.0.12 master version, and make sure your webserver user owns the gpx dir completely in your webserver root?

**Comment by devryan** [comment]
No reply after, closing
