### ISSUE TITLE
Cant find the LD Library Path

### ISSUE THREAD

**Issue by KillaSeven** [devryan/GamePanelX-V3#116]
I'm getting this error here:

./srcds_run: 32: ./srcds_run: pushd: not found ./srcds_run: 35: ./srcds_run: popd: not found Server will auto-restart if there is a crash. LD_LIBRARY_PATH=/var/www/vhosts/killer7.de/httpdocs/GamePanelX-V3-master/_SERVER S/accounts/example/178.254.20.158:27015/740/bin:/var/www/vhosts/killer7.de/httpd ocs/GamePanelX-V3-master/_SERVERS/accounts/example/178.254.20.158:27015/740:/var /www/vhosts/killer7.de/httpdocs/GamePanelX-V3-master/_SERVERS/accounts/example/1 78.254.20.158:27015/740/bin: Failed to open libtier0.so (libtier0.so: cannot open shared object file: No such file or directory) Add "-debug" to the ./srcds_run command line to generate a debug.log to help wit h solving this problem Thu Apr 2 04:50:55 CEST 2015: Server restart in 10 seconds

I dont know how I can change the LD Library path, since I'm running plesk on my root to configure my homepages, the path should be different ( I think ) ... So I dont know what I should do :/

**Comment by AldemaroC** [comment]
It's happening because there is a ":" in the directory (178.254.20.158->:<-27015). I solved it changing all scripts to put a dot instead. This way, the server would start as it should.

**Comment by AldemaroC** [comment]
Any guide on how to use github? I'll try to fix some bugs on gpx

**Comment by devryan** [comment]
This has been fixed, see latest commits on master branch of master+remote.  https://github.com/devryan/GamePanelX-V3/commit/29554eb7ed86c81e7fb4a919d4f37ebf5b39c27f
