### ISSUE TITLE
blah/tmp/2/steamcmd No such file or directory

### ISSUE THREAD

**Issue by originalwhitestar** [devryan/GamePanelX-V3#117]
I get this error when installing a source game(gmod):
./steamcmd.sh: line 29: /var/www/gamepanelx/_SERVERS/tmp/2/linux32/steamcmd: No such file or directory
but I see steamcmd per ftp & putty, whats wrong? its not a directory though, its a file without a ending.
the admin section shows Steam install: 0%, wont go further?

**Comment by devryan** [comment]
Do you still have this problem?  If so, what OS, and any other control panels installed?
