### ISSUE TITLE
The server does not turn

### ISSUE THREAD

**Issue by breansdxtr** [devryan/GamePanelX-V3#118]
The server does not turn even when I press start showing me a success message, but the server remains off

**Comment by Cipio1106** [comment]
Hello,

What is the server ?
Did you check if the template is correctly configured ?

**Comment by breansdxtr** [comment]
Hello friend indeed if I followed a video tutorial for configuring everything as is and still gives me the error

**Comment by Cipio1106** [comment]
But what is the server ? A gmod server ? A minecraft server ? A ts3 server ?

**Comment by breansdxtr** [comment]
It is a counter strike server

**Comment by Cipio1106** [comment]
I help you tomorrow. I have to go

**Comment by breansdxtr** [comment]
I really need help urgently, I am creating a company to sell servers counter strike

**Comment by breansdxtr** [comment]
I have solved the problem, thank you very much.
