### ISSUE TITLE
hostname not complete

### ISSUE THREAD

**Issue by breansdxtr** [devryan/GamePanelX-V3#119]
I am having a problem when I create a new counter striker server hostname not complete sample also want to display a custom message Game my business

**Comment by breansdxtr** [comment]
I got the problem, placing the hostname from the panel does not correctly displayed in the file server.cfg without quotation marks and should appear this way "sample hostname" can someone help me solve this problem?

**Comment by Cipio1106** [comment]
I had the same problem.
My solution : Copy and paste into the "server.cfg" file a basic configuration from https://support.steampowered.com/downloads/5386-HMJI-5162/cs_server_cfg_file.cfg

And restart the apache web server & the game server to apply.

**Comment by breansdxtr** [comment]
I've solved the problem

**Comment by Cipio1106** [comment]
So close the issue ^_^
