### ISSUE TITLE
Issues with steam games

### ISSUE THREAD

**Issue by allinonemovie** [devryan/GamePanelX-V3#120]
I can´t install templates of steam games. Every time the status changes from "Steam Running" to "Steam Install 0%" and stucks at 0%. Here are some logs:

_SERVERS/logs/steam.log:
```
SteamCMDInstall: (Sat May  9 11:44:23 EDT 2015) Starting SteamCMD install on dir (/var/www/webinterface//_SERVERS/tmp/2) for game (740) ...
SteamCMDInstall: (Sat May  9 11:44:23 EDT 2015) Downloading steamcmd_linux.tar.gz ...
SteamCMDInstall: (Sat May  9 11:44:23 EDT 2015) Starting SteamCMD authentication check ...
SteamCMDInstall: (Sat May  9 11:44:23 EDT 2015) Steam: force_install_dir: /var/www/webinterface/_SERVERS/tmp/2/740, app_update: 740
SteamCMDInstall: (Sat May  9 11:44:23 EDT 2015) SteamCMD is authed and ready, starting game 740 update ...
SteamCMDInstall: (Sat May  9 11:44:23 EDT 2015) Game installation began on PID (14707)
SteamCMDInstall: (Sat May  9 11:44:23 EDT 2015) While loop forked off to PID (14712)
SteamCMDInstall: (Sat May  9 14:02:32 EDT 2015) Starting SteamCMD install on dir (/var/www/webinterface//_SERVERS/tmp/4) for game (740) ...
SteamCMDInstall: (Sat May  9 14:02:32 EDT 2015) Downloading steamcmd_linux.tar.gz ...
SteamCMDInstall: (Sat May  9 14:02:33 EDT 2015) Starting SteamCMD authentication check ...
SteamCMDInstall: (Sat May  9 14:02:33 EDT 2015) SteamCMD is authed and ready, starting game 740 update ...
SteamCMDInstall: (Sat May  9 14:02:33 EDT 2015) Game installation began on PID (14551)
SteamCMDInstall: (Sat May  9 14:02:33 EDT 2015) While loop forked off to PID (14556)
SteamCMDInstall: (Sat May  9 17:23:36 EDT 2015) Starting SteamCMD install on dir (/var/www/webinterface//_SERVERS/tmp/5) for game (740) ...
SteamCMDInstall: (Sat May  9 17:23:36 EDT 2015) Downloading steamcmd_linux.tar.gz ...
SteamCMDInstall: (Sat May  9 17:23:36 EDT 2015) Starting SteamCMD authentication check ...
SteamCMDInstall: (Sat May  9 17:23:36 EDT 2015) SteamCMD is authed and ready, starting game 740 update ...
SteamCMDInstall: (Sat May  9 17:23:36 EDT 2015) Game installation began on PID (28749)
SteamCMDInstall: (Sat May  9 17:23:36 EDT 2015) While loop forked off to PID (28753)
SteamCMDInstall: (Sat May  9 17:38:59 EDT 2015) Starting SteamCMD install on dir (/var/www/webinterface//_SERVERS/tmp/6) for game (232330) ...
SteamCMDInstall: (Sat May  9 17:38:59 EDT 2015) Downloading steamcmd_linux.tar.gz ...
SteamCMDInstall: (Sat May  9 17:39:07 EDT 2015) Starting SteamCMD authentication check ...
SteamCMDInstall: (Sat May  9 17:40:33 EDT 2015) SteamCMD is authed and ready, starting game 232330 update ...
SteamCMDInstall: (Sat May  9 17:40:33 EDT 2015) Game installation began on PID (32294)
SteamCMDInstall: (Sat May  9 17:40:33 EDT 2015) While loop forked off to PID (32299)
SteamCMDInstall: (Sun May 10 04:31:05 EDT 2015) Starting SteamCMD install on dir (/var/www/webinterface//_SERVERS/tmp/7) for game (740) ...
SteamCMDInstall: (Sun May 10 04:31:05 EDT 2015) Downloading steamcmd_linux.tar.gz ...
SteamCMDInstall: (Sun May 10 04:31:15 EDT 2015) Starting SteamCMD authentication check ...
SteamCMDInstall: (Sun May 10 04:43:02 EDT 2015) Starting SteamCMD install on dir (/var/www/webinterface//_SERVERS/tmp/8) for game (740) ...
SteamCMDInstall: (Sun May 10 04:43:02 EDT 2015) Downloading steamcmd_linux.tar.gz ...
```
_SERVERS/tmp/steam_6.log:
```
Redirecting stderr to '/var/www/webinterface//_SERVERS/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
[1mlogin mysteamname mysteampw
[0m
Logging in user 'mysteamname' to Steam Public...Retrying. . . 
Logged in OK
Waiting for license info...OK
[1mquit
[0m
```
Do you need more log files?

Sorry for my bad english ;)

**Comment by devryan** [comment]
There are a few posts about this, but I cannot reproduce.

What os is this? Any other software/control panels installed?  Any custom apache,php plugins/modules that are running?  What about selinux, is it running?

**Comment by HybridFox** [comment]
I'm having the same issue. i'm on ubuntu 14.04 clean fresh install.
When i check the steam log i see this

`SteamCMDInstall: (Wed Oct 14 08:59:19 EDT 2015) SteamCMD is authed and ready, starting game 740 update ...
SteamCMDInstall: (Wed Oct 14 08:59:19 EDT 2015) Game installation began on PID (7782)
SteamCMDInstall: (Wed Oct 14 08:59:19 EDT 2015) While loop forked off to PID (7786)`

**Comment by Dwingo** [comment]
On my server (Debian 8) the Control Panel shows Status: Installing ... for hours now. But i can start and connect to the installed gameserver
![2015-10-30 10_06_37-admin _ gamepanelx](https://cloud.githubusercontent.com/assets/3104685/10842263/c551ba0a-7ef0-11e5-9c2e-c52b8126443e.png)
.

**Comment by devryan** [comment]
What else is installed on your Debian os? Any other control panels?  Any security web modules installed?

Note that there is a callback that happens, after your server finishes installing, it does a wget back to your master URL.  I would do a "ps -ef | grep CreateServer" and show the output here if you get anything back.

**Comment by Dwingo** [comment]
Thanks for your answer.
I think the problem is, that the GPX callback is a http url request but my server uses https. Is it possible to set https in the config?

**Comment by devryan** [comment]
AHA!  Yep, you're right.  That's a bug.  It shouldn't assume http.  Will get this fixed up.

**Comment by devryan** [comment]
Hey @Dwingo -- I've added in a fix to this in a new branch called 'https_fix', can you check this branch out on the master (after updating to the latest 3.0.12 I pushed out tonight finally), and give it a try?  It should do callbacks over HTTPS now and things should work more normally.

**Comment by slgfire** [comment]
i have the same problem. my steam.log is the same and de callback link is right.
what can i do?

**Comment by sheldor091** [comment]
I have the same Problem. I will give you acces to my server so you can fix it if you want. then you know the problem :)


SteamCMDInstall: (Wed Apr  6 02:34:24 CEST 2016) Starting SteamCMD install on dir (/var/www/html/x030390//_SERVERS/tmp/1) for game (740) ...
SteamCMDInstall: (Wed Apr  6 02:34:24 CEST 2016) Downloading steamcmd_linux.tar.gz ...
SteamCMDInstall: (Wed Apr  6 02:34:25 CEST 2016) Starting SteamCMD authentication check ...
SteamCMDInstall: (Wed Apr  6 02:34:25 CEST 2016) Steam: force_install_dir: /var/www/html/x030390/_SERVERS/tmp/1/740, app_update: 740
SteamCMDInstall: (Wed Apr  6 02:34:25 CEST 2016) SteamCMD is authed and ready, starting game 740 update ...
SteamCMDInstall: (Wed Apr  6 02:34:25 CEST 2016) Game installation began on PID (6268)
SteamCMDInstall: (Wed Apr  6 02:34:25 CEST 2016) While loop forked off to PID (6273)

**Comment by sheldor091** [comment]
But i think its a steamcmd problem. i tried install other gamepanel. When i installed thze steam cmd manually it doesn´t create files on my server.

**Comment by sheldor091** [comment]
This is the problem ithink: 
SteamInstall: (Thu Apr  7 14:07:28 CEST 2016) Downloading hldsupdatetool.bin ...
SteamInstall: (Thu Apr  7 14:07:30 CEST 2016)  Running hldsupdatetool.bin ...
SteamInstall: (Thu Apr  7 14:07:30 CEST 2016) Failed to extract Steam client: 
SteamInstall: (Thu Apr  7 14:07:55 CEST 2016) Downloading hldsupdatetool.bin ...
SteamInstall: (Thu Apr  7 14:07:57 CEST 2016)  Running hldsupdatetool.bin ...
SteamInstall: (Thu Apr  7 14:07:57 CEST 2016) Failed to extract Steam client: 
SteamInstall: (Thu Apr  7 14:17:39 CEST 2016) Downloading hldsupdatetool.bin ...
SteamInstall: (Thu Apr  7 14:17:41 CEST 2016)  Running hldsupdatetool.bin ...
SteamInstall: (Thu Apr  7 14:17:41 CEST 2016) Failed to extract Steam client:

**Comment by Dwingo** [comment]
Thanks @devryan this version works now. I have just testet with a murmur server. The installation works and i can start / stop the murmur server. But the panel shows still "installing". I changed the status in the mysqldb and now everything with murmur is working. I'll test it with steam after my vacations.
![2016-06-21 21_26_42-admin _ gamepanelx](https://cloud.githubusercontent.com/assets/3104685/16243543/12705dbc-37f8-11e6-8830-cf3507520800.png)
![2016-06-21 21_36_17-admin _ gamepanelx](https://cloud.githubusercontent.com/assets/3104685/16243582/41c1f17a-37f8-11e6-8fe4-93af111ae9f0.png)
