### ISSUE TITLE
Check the "docroot" value in /configuration.php

### ISSUE THREAD

**Issue by geryke1** [devryan/GamePanelX-V3#121]
Hi,
Can anyone help?
![bug](https://cloud.githubusercontent.com/assets/12541461/7743884/1a4a7104-ff9f-11e4-8e9f-d0cdd38a9ccc.PNG)

i get this error when i click all servers

**Comment by devryan** [comment]
This means your docroot in configuration.php is wrong.  Did you move your gamepanelx install folder to a new name maybe?  Open the configuration.php file and check the path that is set there, make sure it is a real path to your gamepanelx install.
