### ISSUE TITLE
Problems on install with some variables.

### ISSUE THREAD

**Issue by baxandrei** [devryan/GamePanelX-V3#123]
Error: 
Notice: Undefined index: language in C:\Users\Andrei\Dropbox\!HTTP\!gamecp\install\install_actions.php on line 28

Warning: touch(): Unable to create file /tmp/gpxinstalltmp.txt because No such file or directory in C:\Users\Andrei\Dropbox\!HTTP\!gamecp\install\install_actions.php on line 64

Fatal error: Call to undefined function posix_getpwuid() in C:\Users\Andrei\Dropbox\!HTTP\!gamecp\install\install_actions.php on line 66

**Comment by baxandrei** [comment]
I don`t need support anymore...

**Comment by devryan** [comment]
This is a Linux control panel -- installing on windows will definitely not work.
