### ISSUE TITLE
FTP not workin

### ISSUE THREAD

**Issue by MineZen1** [devryan/GamePanelX-V3#125]
I installed proftpd on the server and gamepanelx and it is not connecting to any account, is there any help?

**Comment by gOOvER** [comment]
Use Easy-WI.... It seem's GPX is dead....

https://easy-wi.com/de/

**Comment by MineZen1** [comment]
easywi ftp doesnt work neither and it got problems too when I asked for help, no one answered me

**Comment by devryan** [comment]
The ftp server is built in. When you run the installer, it asks if you want
to install the ftp server.

**Comment by MineZen1** [comment]
I installed it @devryan but still it didnt work

**Comment by devryan** [comment]
What's not working about it?  When you try to connect to your game server
on port 21 via an ftp client  what happens?

**Comment by MineZen1** [comment]
tells me wrong password and then disconnects

**Comment by devryan** [comment]
@MineZen1, on your server do a "sudo netstat -anp | grep ftp" and show the output here.  Sounds like maybe another FTP server is running.
