### ISSUE TITLE
Failed to open local config for writing

### ISSUE THREAD

**Issue by andrepaandrea** [devryan/GamePanelX-V3#127]
Everytime I try to start the server I get this:
Failed: Failed to open local config (/var/www/html/Web-I//_SERVERS/accounts/PublicServer/xxx.xxx.xxx.xx:27015/740/csgo/cfg/server.cfg) for writing.

**Comment by devryan** [comment]
Does the file actually exist?  What are your permissions on that directory, can you "ls -l" the _SERVERS directory?

**Comment by mlaraibyameen** [comment]
change the ownership of file to www-data or apache, and if the file doesn't exist create an empty file and do the same.

**Comment by devryan** [comment]
No reply after, closing
