### ISSUE TITLE
Unable to run Battlefield 2 Server With Gamepanel

### ISSUE THREAD

**Issue by hacktrix2006** [devryan/GamePanelX-V3#128]
So i have done two tests here.

After Creating the template for BF2 i made a user and for the sake of this we will call it user101. This completes and i create a server for BF2 which downloads and extract just as it should on the remote box.

Now in the folder on remote /usr/local/gpx/users/user101/<ip address>/ all the files are there however running ./start.sh see's the error about unable to access a shared file called libdice_y.so even though the file is there in the /bin/amd-64/ and /bin/ia-32/ folders.

Put if i make a new users via SSH called user102 and copy the files from users101 folder and chown the files for user102 and i type ./start.sh it works and boots the BF2 Server.

If i try to access user101 via FTP it will fail and the same with SSH on user101 as it states the username doesn't exist yet on the same box i can ssh and ftp in to user102 which was created via ssh.

So there is something happening on user creation and it does't matter if this is done on the master or remote boxes the same issue applies.

I am using Ubuntu 15.04 server 64bit

**Comment by siasur** [comment]
Hey, could you please attach the start.sh file? Oh and could you send the full path of both directories (path to start.sh on user 101 and path to start.sh on user 102)

**Comment by hacktrix2006** [comment]
Full path on user101 

/usr/local/gpx/users/user101

Full path on user102 via adduser command in ssh

/home/user102

The ./start.sh has just

#! /bin/sh

MACH=""
# 64-bit FreeBSD is "amd64"; emulates 32-bit Linux.
case `uname -m` in
	i[3456]86 | amd64) MACH="ia-32"
	;;
	x86_64) MACH="amd-64"
	;;
esac

if ! [ -d pb ]
then
	ln -s pb_$MACH pb
fi

BINARY_DIR="$(pwd)/bin"
if [ -d "$BINARY_DIR/$MACH" ]
then
	BINARY_DIR="$BINARY_DIR/$MACH"
fi

# Make the OS give us .core-dumps if the server crashes
ulimit -c unlimited

export LD_LIBRARY_PATH=$BINARY_DIR
exec $BINARY_DIR/bf2 "$@"

**Comment by siasur** [comment]
Thanks for the reply.
Are this really the full pathes to the `start.sh`? If you use gpx your path should be something like `/usr/local/gpx/users/user/127.0.0.1:1337` that's why I asked for the full path __of the start.sh file__.

And in addition, the startscript is very hard to read thanks to markdown, that's why I asked you to attach it.

If you have a path like in my example i already found you problem.
But to be sure you need to tell me both full pathes to the `start.sh`. (not to the user)

**Comment by hacktrix2006** [comment]
/usr/local/gpx/users/user101/<ip>:<port> 

the user102 was a test user.

So how does one fix the issue

Sorry about the markdown i haven't used github before so here a link to the file http://www.ultrahostinguk.co.uk/start.sh

Thanks for your time

**Comment by siasur** [comment]
Wait for my fix in the GamePanelX-V3-Remote Repo. I have to test it today and if it's merged your problem will be solved (after a update)

**Comment by hacktrix2006** [comment]
Thank you

**Comment by hacktrix2006** [comment]
Looked at your changed and notice that it will work but the WebGUI on the master will not get access to the FTP tab just a heads up. Also the changes will need to go into the Master repo as well for the same files that you edited.

**Comment by siasur** [comment]
Thanks for pointing out that. It's so obvious, that i missed it completely.
I'll finish the reinstall of my homeserver, apply the changes to the WebGUI and then test it.

So... it's possible that my changes won't be merged today.

**Comment by hacktrix2006** [comment]
No problem bud, as confirmed i pulled your branch which was two commits ahead for the remote and the BF2 server is running great but although the User's FTP  works through an FTP client so long as you place gpx infront for example gpxuser101. But the WebGUI's panel is just a white box but other then that its working great on my Hyper-V server. Nice work on the fix too.

**Comment by siasur** [comment]
So basically you are saying that my fix is partial working?
That's nice to hear! :)

maybe you could add a comment with your positive feedback to my pull request (but include the information that the WebGUI needs changes too)

**Comment by hacktrix2006** [comment]
Yep it is working like a champ i.e you can start and stop the server without issues. The user is now FTP Clientable to upload files and download files. The BF2 Query still shows the server offline though and the FTP in the GUI doesn't work. I have also noticed that the settings for BF2 do not work i had to manually change the serversettings.con file etc no big but over all its getting there.

**Comment by hacktrix2006** [comment]
Closed it by mistake!

**Comment by siasur** [comment]
reopen it ^^

**Comment by hacktrix2006** [comment]
ah i see it!

**Comment by devryan** [comment]
Hi!  What's the status of this, what pull request is this @siasur ?

**Comment by hacktrix2006** [comment]
This issue with fixed with the colonfix which has since been merged in the dev branch i think

**Comment by siasur** [comment]
Yep ^^
@devryan already merged it into the dev branch

**Comment by hacktrix2006** [comment]
Rebuilding my Hyper-V images to use Dev branch tonight so that i can help/test fixes.

**Comment by devryan** [comment]
@hacktrix2006 see the ip_port_fix branch in the master, it has the fixes
there too for the complete solution. If you want to test them together that
would be the proper way. I've tested myself and it's working great for
csgo.

**Comment by devryan** [comment]
This has been fixed, see latest commits on master branch of master+remote.  https://github.com/devryan/GamePanelX-V3/commit/29554eb7ed86c81e7fb4a919d4f37ebf5b39c27f
