### ISSUE TITLE
Steam files are downloaded on update for non steam game

### ISSUE THREAD

**Issue by fritz-net** [devryan/GamePanelX-V3#131]
If I press update on a server I see in that the steam files are added and I'm not sure if the update is done ( the update is an .sh file which I think is not run)

in the ./includes/classes/servers.php on line 248 is checked if its a steam game or not so I'm not sure if its an panel or remote bug. both are ubuntu14.04 server

EDIT1:
the remote steam.log:
     SteamCMDInstall: (Mo 11. Jan 02:08:07 CET 2016) Starting SteamCMD authentication check ...
     SteamCMDInstall: (Mo 11. Jan 02:08:07 CET 2016) Steam: force_install_dir: /usr/local/gpx/users/xyz/1.2.3.4.5/, app_update:
     SteamCMDInstall: (Mo 11. Jan 02:08:07 CET 2016) SteamCMD is authed and ready, starting game  update ...
     SteamCMDInstall: (Mo 11. Jan 02:08:07 CET 2016) Game installation began on PID ()

EDIT2: maybe i found the bug in the remote part the UpdateServer.sh on line 92 steam is called even for non steam games

**Comment by gOOvER** [comment]
GamePanelx is not longer Maintained. 

Try Easy-WI -> https://easy-wi.com/

**Comment by devryan** [comment]
I've merged your fix
