### ISSUE TITLE
New Game Server Status

### ISSUE THREAD

**Issue by cpt-fred** [devryan/GamePanelX-V3#134]
Hello,

I started to use gamepanelx and it works fine! 
Otherwise i have some issues with the function "server status"!

I would like to know, how the "server status" is updated! Because i have build a own template of arma3 with ports and the process arma3server, but it always appears as offline! But the server is running good and players can join. 

The problem is that in the web interface the server appears offline instead of online.

Any help for that?

Regards,
Fred

**Comment by mlaraibyameen** [comment]
Dear Fred,

Game Panels use source engine to identify current status of servers.

Kindly set "Query Engine" to arma3 or if arma3 is not on the list select the similar or look alike game's engine. and status will started to work.

**Comment by devryan** [comment]
No reply after, closing
