### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Zortex04** [devryan/GamePanelX-V3#137]
When pressing install in Websitename/install it comes up with this error
Error: 
Notice: Undefined index: language in D:\Programs\Xampp\htdocs\install\install_actions.php on line 28

Warning: touch(): Unable to create file /tmp/gpxinstalltmp.txt because No such file or directory in D:\Programs\Xampp\htdocs\install\install_actions.php on line 64

Fatal error: Call to undefined function posix_getpwuid() in D:\Programs\Xampp\htdocs\install\install_actions.php on line 66

**Comment by devryan** [comment]
This control panel is not for Windows.

**Comment by Zortex04** [comment]
ah thats why :+1:  Thats for saying t hat
