### ISSUE TITLE
Steam Install 0% STOP

### ISSUE THREAD

**Issue by domino1281** [devryan/GamePanelX-V3#140]
Hi , I'm Dominik I have a problem. Sorry Bad English :dancer: 

'm waiting just 10 minutes and nothing . Please Help !! :(

Folder Logs
File steam.txt

SteamCMDInstall: (Fri Apr  8 10:37:26 CEST 2016) Starting SteamCMD install on dir (/var/www/panel//_SERVERS/tmp/34) for game (232250) ...
SteamCMDInstall: (Fri Apr  8 10:37:26 CEST 2016) Downloading steamcmd_linux.tar.gz ...
SteamCMDInstall: (Fri Apr  8 10:37:38 CEST 2016) Starting SteamCMD authentication check ...
SteamCMDInstall: (Fri Apr  8 10:37:38 CEST 2016) SteamCMD is authed and ready, starting game 232250 update ...
SteamCMDInstall: (Fri Apr  8 10:37:38 CEST 2016) Game installation began on PID (13710)
SteamCMDInstall: (Fri Apr  8 10:37:38 CEST 2016) While loop forked off to PID (13713)

Folder Tmp 
File steam_35.log

Redirecting stderr to '/var/www/panel//_SERVERS/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
[1mlogin ******** **********
[0m
Logging in user 'malina1281' to Steam Public...Logged in OK
Waiting for license info...OK
[1mquit
[0m

**Comment by gOOvER** [comment]
https://easy-wi.com/

**Comment by mlaraibyameen** [comment]
I don't know why this happen but here is what you can do to create server template.

Suppose you want to create a template for Counter Strike 1.6 and you installation directory is /var/www/html/

1: create directory "cs16" in /var/www/html
2: put steamcmd in cs16 directory and download game in same directory
3: now create a game template and set "File Path" to "/var/www/html/cs16" and hit enter.
4: then wait for 10 seconds and reload the GamePanelX web page.
5: Done.

Now you'll see game template is successfully created and you can move forward to create you Game Server.

and if you face any problem feel free to contact me. 

P.S
Sorry for my bad english

**Comment by devryan** [comment]
No reply after, closing
