### ISSUE TITLE
install 0%

### ISSUE THREAD

**Issue by jonas9105** [devryan/GamePanelX-V3#141]
Hi, Jonas here!

I installed GamePanelX
I want a CS:GO Server....
I made a Template for my CS:GO Server...
It said: Steam_Running
*Refrshing some times*
At least it says: install 0% and never moving or something?

STEAM.log

SteamCMDInstall: (Sat Apr 30 20:50:16 UTC 2016) Starting SteamCMD install on dir (/var/www/html/GamePanelX-V3-master//_SERVERS/tmp/3) for game (740) ...
SteamCMDInstall: (Sat Apr 30 20:50:16 UTC 2016) Downloading steamcmd_linux.tar.gz ...
SteamCMDInstall: (Sat Apr 30 20:50:16 UTC 2016) Starting SteamCMD authentication check ...
SteamCMDInstall: (Sat Apr 30 20:50:16 UTC 2016) Steam: force_install_dir: /var/www/html/GamePanelX-V3-master/_SERVERS/tmp/3/740, app_update: 740
SteamCMDInstall: (Sat Apr 30 20:50:16 UTC 2016) SteamCMD is authed and ready, starting game 740 update ...
SteamCMDInstall: (Sat Apr 30 20:50:16 UTC 2016) Game installation began on PID (4259)
SteamCMDInstall: (Sat Apr 30 20:50:16 UTC 2016) While loop forked off to PID (4263)

TEMPLATES.log

CreateTemplate: (Sat Apr 30 20:18:53 UTC 2016) Connecting to callback URL (http://176.58.122.78/GamePanelX-V3-master/includes/callback.php?token=Y6lmyZBBlLHacuED&id=2&do=tpl_status&status=started) ...
CreateTemplate: (Sat Apr 30 20:18:53 UTC 2016) Beginning archive of template directory (/var/www/html/GamePanelX-V3-master//_SERVERS/tmp/2) ...
CreateTemplate: (Sat Apr 30 20:18:53 UTC 2016) Archive of template directory started (Script PID 3726, tar PID 3732) ...
CreateTemplate: (Sat Apr 30 20:18:53 UTC 2016) Check while loop forked off to PID: 3734
CreateTemplate: (Sat Apr 30 20:18:56 UTC 2016) Archive creation completed
CreateTemplate: (Sat Apr 30 20:18:56 UTC 2016) Running callback url for completed

SERVERS.log

Sat Apr 30 20:22:56 UTC 2016 ubuntu CreateServer: Creating server directory /var/www/html/GamePanelX-V3-master//_SERVERS/accounts/nikkinice/176.58.122.78.25565 ...
Sat Apr 30 20:22:56 UTC 2016 ubuntu CreateServer: Extracting TPL (2) to /var/www/html/GamePanelX-V3-master//_SERVERS/accounts/nikkinice/176.58.122.78.25565 ...
Sat Apr 30 20:23:04 UTC 2016 ubuntu Restart: Restarting 176.58.122.78.25565 for user nikkinice ...
Sat Apr 30 20:23:04 UTC 2016 ubuntu Restart: Warning: No GNU Screen found!  Please install screen to use all server features.
Sat Apr 30 20:23:10 UTC 2016 ubuntu Restart: Restarting 176.58.122.78.25565 for user nikkinice ...
Sat Apr 30 20:23:11 UTC 2016 ubuntu Restart: Warning: No GNU Screen found!  Please install screen to use all server features.
Sat Apr 30 20:23:24 UTC 2016 ubuntu ServerOutput: No GNU Screen found, tailing log (/var/www/html/GamePanelX-V3-master//_SERVERS/accounts/nikkinice/176.58.122.78.25565/.gpxsrv.log) ...
Sat Apr 30 20:33:16 UTC 2016 ubuntu ServerOutput: No GNU Screen found, tailing log (/var/www/html/GamePanelX-V3-master//_SERVERS/accounts/nikkinice/176.58.122.78.25565/.gpxsrv.log) ...
Sat Apr 30 20:33:38 UTC 2016 ubuntu ServerOutput: No GNU Screen found, tailing log (/var/www/html/GamePanelX-V3-master//_SERVERS/accounts/nikkinice/176.58.122.78.25565/.gpxsrv.log) ...
Sat Apr 30 20:34:22 UTC 2016 ubuntu ServerOutput: No GNU Screen found, tailing log (/var/www/html/GamePanelX-V3-master//_SERVERS/accounts/nikkinice/176.58.122.78.25565/.gpxsrv.log) ...
Sat Apr 30 20:36:27 UTC 2016 ubuntu Restart: Restarting 176.58.122.78.25565 for user nikkinice ...
Sat Apr 30 20:36:28 UTC 2016 ubuntu Restart: Warning: No GNU Screen found!  Please install screen to use all server features.
Sat Apr 30 20:36:53 UTC 2016 ubuntu Restart: Restarting 176.58.122.78.25565 for user nikkinice ...
Sat Apr 30 20:36:54 UTC 2016 ubuntu Restart: Warning: No GNU Screen found!  Please install screen to use all server features.
Sat Apr 30 20:37:03 UTC 2016 ubuntu ServerOutput: No GNU Screen found, tailing log (/var/www/html/GamePanelX-V3-master//_SERVERS/accounts/nikkinice/176.58.122.78.25565/.gpxsrv.log) ...
Sat Apr 30 20:37:07 UTC 2016 ubuntu ServerOutput: No GNU Screen found, tailing log (/var/www/html/GamePanelX-V3-master//_SERVERS/accounts/nikkinice/176.58.122.78.25565/.gpxsrv.log) ...
Sat Apr 30 20:44:52 UTC 2016 ubuntu Restart: Restarting 176.58.122.78.25565 for user nikkinice ...
Sat Apr 30 20:44:52 UTC 2016 ubuntu Restart: Warning: No GNU Screen found!  Please install screen to use all server features.
Sat Apr 30 20:45:37 UTC 2016 ubuntu ServerOutput: No GNU Screen found, tailing log (/var/www/html/GamePanelX-V3-master//_SERVERS/accounts/nikkinice/176.58.122.78.25565/.gpxsrv.log) ...
Sat Apr 30 20:53:24 UTC 2016 ubuntu Restart: Restarting 176.58.122.78.25565 for user nikkinice ...
Sat Apr 30 20:53:26 UTC 2016 ubuntu Restart: Warning: No GNU Screen found!  Please install screen to use all server features.

HOW DO I FIX?

**Comment by gOOvER** [comment]
gpx is not maintained. 

Try Easy-WI:   https://easy-wi.com/

**Comment by mlaraibyameen** [comment]
I don't know why this happen but here is what you can do to create server template.

Suppose you want to create a template for Counter Strike 1.6 and you installation directory is /var/www/html/

1: create directory "cs16" in /var/www/html
2: put steamcmd in cs16 directory and download game in same directory
3: now create a game template and set "File Path" to "/var/www/html/cs16" and hit enter.
4: then wait for 10 seconds and reload the GamePanelX web page.
5: Done.

Now you'll see game template is successfully created and you can move forward to create you Game Server.

and if you face any problem feel free to contact me. 

P.S
Sorry for my bad english

**Comment by devryan** [comment]
Also, it complained a million times about not having Gnu Screen, try installing that, it works much better when it can use it
