### ISSUE TITLE
Account Issue

### ISSUE THREAD

**Issue by Zortex04** [devryan/GamePanelX-V3#142]
recently i installed gamepanelx on my ubuntu pc Btw this is second try cause this happend first time too

After installing after setting up database
after deleting install
it says login failed when i login with the account i setup in the installing part, this is second time this happend I myself dont know whats wrong please help

**Comment by siasur** [comment]
Try it again with a password that only uses a-Z and 0-9

**Comment by mlaraibyameen** [comment]
when you install GamePanelX the form requires you to enter Admin user and password, after successful installation and deleting install directory, there are 2 Login Forms,
1: http://your-server-ip-or-host/     (for user login)
2: http://your-server-ip-or-host/admin/     (for admin login)

the username and password that you enter while installing GamePanelX will work only in Admin Login Area, and then you can create additional users or admins, admins can login only from Admin Area and users can login only from user login area.

P.S
Sorry for my bad english.
