### ISSUE TITLE
Creating a TeamSpeak3 TEMPLATE server

### ISSUE THREAD

**Issue by Roxxas** [devryan/GamePanelX-V3#143]
Hello ! I was trying to make a template for the teamspeak3 server and then It said https://gyazo.com/5b3e00e7d559a1e25b2f06919d79e039

Can you guys help me ?

**Comment by mlaraibyameen** [comment]
Roxxas follow this link for successful setup of Team Speak 3 Server.

https://www.youtube.com/watch?v=33kYnU8DK8Y
