### ISSUE TITLE
Requesting Takeover of Project

### ISSUE THREAD

**Issue by TekkitCommando** [devryan/GamePanelX-V3#145]
Hello @devryan my team and I at Byte Powered (there are 4 of us) would like to take over this project as well as the WHMCS plugin that you have made for it. We understand you would like to interview us on our skills in php/bash and different operating systems. We can talk to you over skype if that is good for you. 

My Skype ID: ethan.smith184 

My GitHub: https://github.com/TekkitCommando <-- PHP Developer
Toby: https://github.com/DefinitlyEvil <-- PHP Developer
Luke: https://github.com/TheDiamondYT1 <-- PHP Developer and Bash Scripter
Phillip Mackintosh: https://github.com/phillmac <-- Sys Admin and Bash Scripter

(More private repos can be shown via Skype.)

**Comment by TheDiamondYT1** [comment]
:+1:

Hope we get permission to takeover

**Comment by devryan** [comment]
Hmm.  Shoot me an email at rdgehrig at gmail, let's talk about it privately

**Comment by TekkitCommando** [comment]
@devryan Thank you! I have sent you an email :)

**Comment by shqipepp** [comment]
Hopefully you then continue updating gpx, as it's the best gamepanel! I also have really cool ideas what you guys could add in gpx! IF you take this project over, please contact me at shqipepp@gmail.com I will tell you my ideas!

**Comment by TekkitCommando** [comment]
@shqipepp Okay! Hopefully after we get in a Skype meeting with @devryan he will be convinced to stay and come back to working on GPX with us as a team member :) We are all up for new ideas :D

**Comment by fritz-net** [comment]
Why not making an fork, start improving there, and then talk about taking over?

**Comment by TekkitCommando** [comment]
@fritz-net We are already talking to @devryan and if we were to fork it and go off on our own he would not benefit from it and we want him to still be able to benefit from GPX as well. We are hoping for a voice meeting with him soon.

**Comment by shqipepp** [comment]
@TekkitCommando Yesterday i also made a post in GPX forum. These are 2 Features which would be really good to have in GPX. Check the post out for yourself: https://gamepanelx.com/forums/viewtopic.php?f=14&t=5128

**Comment by devryan** [comment]
@shqipepp thanks for the post - although there are already FTP accounts included if you use GPX Remote, the only difference from your request is that the FTP account is per-user, not per-server.  So the user owning the game servers gets their own FTP account and can add/replace files using their GPX account credentials.

**Comment by devryan** [comment]
I also agree with @fritz-net, adding a few commits even as fixes would be an awesome start :+1:

**Comment by TheDiamondYT1** [comment]
@devryan Alright. We have forked the repos to https://github.com/bytepowered/

**Comment by devryan** [comment]
You rock @TheDiamondYT1.  Send a few fixes my way, I can approve and we'll be off running

**Comment by TekkitCommando** [comment]
@devryan Alright, we will start working on the software and send some PR's your way. Also, I am sending you an email about possible options for boosting the growth rate of GPX support as far as users and finances. Let me know what you think about them and we can talk about implementing in the future once these PR's are sent and we are looking into the future.

**Comment by shqipepp** [comment]
Im so excited to see you guys working together. I wish you best luck with your work!

**Comment by TekkitCommando** [comment]
@shqipepp Thanks :)

**Comment by TheDiamondYT1** [comment]
I cant believe this issue was only 3 months ago! Is the project maintained now @devryan? I see you have removed the message stating that its not actively maintained.

**Comment by devryan** [comment]
@TheDiamondYT1 I removed that message when I started working on it again.

The reason updates are slow, the changes that will come are big ones, specifically the changing of how user passwords are stored, changing the use of SSH user/pass, I want to make this thing much more secure.  I need to do recon on who's interested in updates from this panel, I don't want to spend time on it if nobody is using it anymore :) it's been a while since I looked at my stats.

**Comment by rststeam** [comment]
> @devryan Alright. We have forked the repos to https://github.com/bytepowered/

Where is that new updates i'm interested

**Comment by TekkitCommando** [comment]
@rststeam We moved it to a new repo. However I decided to slowly make a new panel from scratch.

**Comment by TheDiamondYT1** [comment]
Im out.

**Comment by rststeam** [comment]
@tekido Open Source or paid? I would like to continue my hosting project but nowadays there is not good panel around

**Comment by TekkitCommando** [comment]
@rststeam, it will have a free and paid plan. I haven't decided for sure yet but it will possibly be free for 1 machine and pay per machine after that. Which is cheaper then your usual pay per server or flat fee stuff.

**Comment by rststeam** [comment]
Any website or some place where features are announced? Any WIP or anything.

**Comment by TekkitCommando** [comment]
@rststeam I haven't made a site yet. The Github organization link is https://github.com/gamesuite but no code code is uploaded yet. You can still watch things though.

That's all I can say. I don't want to be advertising on Ryan's repo issues.
