### ISSUE TITLE
Error Steam Game install

### ISSUE THREAD

**Issue by stevealexandre** [devryan/GamePanelX-V3#149]
Hello,

Your panel is really great and more functional than other.
Unfortunately, I have an issue like many people as I can see and I have tried to resolved it by myself since 3hours but it's time to give up and ask to you a support ...
I have search in forum & issues(here), but I haven't found my solution :(.

I'm block like some peoples at 0% with status steam_running and size Unknown

Server : Debian 8.5 Stable Last Build
All package needed are installed(php5, mysql, etc...)

Here my logs files :

**-steam_ID.log**

```
Redirecting stderr to '/var/www/gamepanel//_SERVERS/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
[1mlogin Sephi314 ######**(Here my password is hidden by myself for this issue)**
[0m
Logging in user 'Sephi314' to Steam Public...Logged in OK
Waiting for license info...OK
[1mquit
[0m
```

**-stderr.txt**
`Empty`

-Steam.log

```
SteamCMDInstall: (Fri Aug 26 03:09:14 CEST 2016) Starting SteamCMD install on dir (/var/www/gamepanel//_SERVERS/tmp/14) for game (740) ...
SteamCMDInstall: (Fri Aug 26 03:09:14 CEST 2016) Downloading steamcmd_linux.tar.gz ...
SteamCMDInstall: (Fri Aug 26 03:09:53 CEST 2016) Starting SteamCMD authentication check ...
SteamCMDInstall: (Fri Aug 26 03:09:55 CEST 2016) SteamCMD is authed and ready, starting game 740 update ...
SteamCMDInstall: (Fri Aug 26 03:09:55 CEST 2016) Game installation began on PID (25601)
SteamCMDInstall: (Fri Aug 26 03:09:55 CEST 2016) While loop forked off to PID (25605)
```

-Template.log

```
CreateTemplate: (Fri Aug 26 01:11:13 CEST 2016) Connecting to callback URL (http://192.168.1.3/gamepanel/includes/callback.php?token=bALMv3GwnoOUM4Vh&id=1&do=tpl_status&status=started) ...
CreateTemplate: (Fri Aug 26 01:11:13 CEST 2016) Beginning archive of template directory (/var/www/gamepanel//_SERVERS/templates) ...
CreateTemplate: (Fri Aug 26 01:11:13 CEST 2016) Archive of template directory started (Script PID 10488, tar PID 10493) ...
CreateTemplate: (Fri Aug 26 01:11:13 CEST 2016) Check while loop forked off to PID: 10496
CreateTemplate: (Fri Aug 26 01:11:16 CEST 2016) Archive creation completed
CreateTemplate: (Fri Aug 26 01:11:16 CEST 2016) Running callback url for completed
```

If you need more logs, tell me and I will give you the necessary.
I'm really tired, it's the third panel which I'm trying to install and again a problem but than other, you're is just a cfg pb that i'm pretty sure you will arrive to help me to correct it.

**Comment by devryan** [comment]
Yeah, this issue happens for a ton of people.

The best thing to do, is to run the game install commands that you see in the Template for CS go under Automation tab, and see what the actual error is.  That SHOULD be logged though, and if it isn';t I need to fix that.

**Comment by theSfr** [comment]
Any news @devryan ?

**Comment by devryan** [comment]
There is a steam CMD log, located here: $HOME/tmp/steam_$tpl_id.log

So if using local mode, this would either be in the ajax/tmp/ directory, or the _SERVERS/tmp, or if using remote, /usr/local/gpx/tmp/

Paste here if you can find it.

**Comment by devryan** [comment]
You know what, this log needs to be streamed straight to the web browser.  Too many people are having this problem. I'll start working on this.

Also, is this a dedicated server, VM, where is this hosted, just out of curiousity?

**Comment by theSfr** [comment]
Here the log requested :
```
Redirecting stderr to '/var/www/gamepanel//_SERVERS/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
[1mlogin anonymous
[0m
Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
[1mforce_install_dir /var/www/gamepanel/_SERVERS/tmp/21/740
[0m[1mapp_update 740 -validate
[0m Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '740' state is 0x202 after update job.
[1mquit
[0m
```

It's a dedicated server on a personnal computer host in my room. (I5 4670K) local mode only so.
Debian 8.5 up to date.

**Comment by devryan** [comment]
Ah-ha!

Yeah, that is a super common problem with the steamcmd utility.  Note the "Error! App '740' state is 0x202 after update job."

That's the problem.  You can fix it by re-running it over and over again until it installs.  I am not sure why this bug still exists with the Steam framework.

Is the /var/www/gamepanel/_SERVERS/tmp/21/740 directory still there?  What's inside it?

**Comment by devryan** [comment]
There are a lot of steam discussions on that: https://steamcommunity.com/discussions/forum/13/864959336482275679/

**Comment by theSfr** [comment]
Yes directory still there and a part of csgo files are present !
But it's weird cause if i'm trying with steamcmd directly from valve website and try install csgo, I have not this issue =X

**Comment by devryan** [comment]
Is apparmor enabled on your system maybe?  What's your disk space like?

Also, if you go into the install directory (/var/www/gamepanel/_SERVERS/tmp/21/740), can you paste what's in there?

**Comment by theSfr** [comment]
I have reinstall all my server because I made a big mistake (chmod on / :+1: )
For moment, I got an other result from last time from steam.sh ... :
`Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
Unpack runtime failed, error code 1
Error:
Couldn't set up the Steam Runtime. Are you running low on disk space?
Continuing...
Press enter to continue:
./steam.sh: ligne 473: /var/www/gamepanel/_SERVERS/tmp/1/ubuntu12_32/steam: No such file or directory
Error:
Couldn't start bootstrap and couldn't reinstall from /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz.  Please contact technical support.
Press enter to continue:`

From steamcmd.sh
`./steamcmd.sh: ligne 34: /var/www/gamepanel/_SERVERS/tmp/1/linux32/steamcmd: No such file or directory`

**Comment by theSfr** [comment]
I made a mistake so I had to reinstalled all my server (chown / :+1: )
After reinstall new weird error ... :
```
Running Steam on debian 8 64-bit
STEAM_RUNTIME is enabled automatically
Unpack runtime failed, error code 1
Error:
Couldn't set up the Steam Runtime. Are you running low on disk space?
Continuing...
Press enter to continue:
./steam.sh: ligne 473: /home/www-data/gamepanel/_SERVERS/tmp/1/ubuntu12_32/steam: Aucun fichier ou dossier de ce type
Error:
Couldn't start bootstrap and couldn't reinstall from /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz.  Please contact technical support.
Press enter to continue:
```

**Comment by xognovalis** [comment]
Do you have ia32libs installed on your dedicated machine?

**Comment by theSfr** [comment]
I don't know how I have done the template but it's ok now xD.
Maybe by forcing by myself with the steamcmd, don't know...
I'm installing server right :+1:

**Comment by theSfr** [comment]
Server installed with success and work !
I have tried a second template and same, all is ok.

here some trails to follow :
1) I have installed steam with all his dependencies
2) I have tried to update directly from steamcmd for the first template (i'm not sure if this has do something or if the web gui was in progress)

**Comment by thesgamingfr** [comment]
Hello dude,
It was a long time :)
Fresh install of my server with fresh install of the panel with your tuto.
Template at 0% with this error in the tmp log : 

> ./steamcmd.sh: line 29: /usr/games/GamePanelX-V3/_SERVERS/tmp/2/linux32/steamcmd: No such file or directory

linux32 existed into 2 dir and steamcmd file too.

**Comment by aqzsedd** [comment]
Hi guys,

JFYI, I had the same issue, and I solved it by adding more disk space!
Make sure that more than 10GB are available! ;)

Enjoy
