### ISSUE TITLE
Failed to start CS:GO 740

### ISSUE THREAD

**Issue by icecrystal99** [devryan/GamePanelX-V3#150]
Hello,

My CS:GO server wont run. When i press on the "**Restart**" button, the server stay offline. And when i check the server.log i see the following line:

> Wed Sep 14 03:42:29 CEST 2016 csgoserver ServerOutput: Sorry, server log doesnt exist.
Wed Sep 14 03:42:54 CEST 2016 csgoserver Restart: Restarting XX.XX.XXX.XXX.27015 for user example.
Wed Sep 14 03:42:55 CEST 2016 csgoserver Restart: Failed to start GNU Screen, no PID!  Exiting.

Did someone how i can fix this ?

Thanks.

**Comment by devryan** [comment]
Did your template, when you created it, go through all the percentages and take a while to install or was it instant?

**Comment by devryan** [comment]
No response, closing

**Comment by VAVANO** [comment]
Can this please be reopened? I' Having same issues...
