### ISSUE TITLE
Error: Failed to create user: Field 'last_updated' doesn't have a default value

### ISSUE THREAD

**Issue by BeFreezy** [devryan/GamePanelX-V3#151]
During installation.

**Comment by skeeta92** [comment]
how do I fix this error "Error: error, Internal Server Error"

**Comment by Fehler404** [comment]
@BeFreezy @skeeta92 It's bc u have "MySQL Strict Mode" enabled.

Fix:
1. Edit ur my.cnf -> Can either be found under /etc/my.cnf or /etc/mysql/my.cnf
2. Insert `[mysqld]
sql_mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"`

Should look like this:
![this](https://cloud.githubusercontent.com/assets/14951074/19415804/a3da7be0-937c-11e6-82d8-9d4421dc475b.jpg)

**Comment by skeeta92** [comment]
That line doesn't exist... do I need to just add it ?

**Comment by Fehler404** [comment]
Yes

**Comment by skeeta92** [comment]
Still no luck :/

**Comment by devryan** [comment]
You restarted mysqld after your change?  What mysql server version and flavor is it?

Note that gpx is not tested against strict mode-enabled mysql so you may need to tweak some things.

**Comment by devryan** [comment]
This is being hosted on a hosting control panel other than gpx -- can't support it if I don't know how it works or what it blocks

**Comment by sterrek** [comment]
Hi, i have to same problem im searching for a few hours. i could provide you the details of my vps
