### ISSUE TITLE
Error: error, Internal Server Error

### ISSUE THREAD

**Issue by skeeta92** [devryan/GamePanelX-V3#152]
Forums are down....anybody know the fix for this?

**Comment by TNovalis** [comment]
Are you using PHP 7?

**Comment by skeeta92** [comment]
No sir 5.6 Centos 7 with Sentora Panel

**Comment by skeeta92** [comment]
Im using MariaDB

**Comment by devryan** [comment]
Typically when GPX is used under a hosting software, there are problems with mixing the two.  Usually web panels have some security plugins enabled that don't allow gpx's internal functions to run.  Check your panel's access and error log and see what the actual error is (Internal Server Error) just means check your logs for the actual issue

**Comment by skeeta92** [comment]
PHP Fatal error:  Call to undefined function posix_getpwuid() in /var/sentora/hostdata/zadmin/public_html/netserj_com/gpx/install/install_actions.php on line 66

**Comment by devryan** [comment]
Make sure php-posix package is installed and reinstall apache after

**Comment by devryan** [comment]
@skeeta92 you have yum repo dependency problems you need to fix. That has nothing to do with gpx.
