### ISSUE TITLE
Expression error

### ISSUE THREAD

**Issue by TheFox1312** [devryan/GamePanelX-V3#158]
Im getting an error when i try to login but after reloading the site im logged in.

Login Failed: Failed to query for plugins: Expression #1 of ORDER BY clause is not in SELECT list, references column 'gpx.plugins.name' which is not in SELECT list; this is incompatible with DISTINCT

Also i cant create templates.

Failed to query for games: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gpx.d.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by Wimmie13** [comment]
Login fix: 
Go to includes/classes/plugins.php and change line 128 to this:
`$result_ac  = @mysql_query("SELECT DISTINCT intname FROM plugins WHERE active = '1' ORDER BY ` **intname** `ASC") or die('Failed to query for plugins: '.mysql_error());`
It said that he tried to order by **name** which is not selected by the query, it should be **intname**.

Templates fix:
Go to admin/games.php and change line 44 to this:
**d.id**
**t.cfgid** is not in the select piece of the query, so it should be **d.id**

**Comment by wasn325** [comment]
Can you help me with this problem ?:

Failed to query for games: Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gpx.n.ip' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

It happens, when I try to add a server and choose the network

**Comment by wasn325** [comment]
Sorry I mean the server

**Comment by wasn325** [comment]
And If I try to ad a template no network is shown up

**Comment by devryan** [comment]
Which version of MySQL are you running?  Any special config options, what
type of server is this?  Standalone, shared hosting, etc?

**Comment by wasn325** [comment]
Mysql:  5.7.20
standalone

**Comment by wasn325** [comment]
![screenshot 115](https://user-images.githubusercontent.com/30980936/34225272-14edc7a0-e5c6-11e7-988f-ce7bd77f536e.png)
I mean this

**Comment by wasn325** [comment]
ok fixed the problem. It was sql_mode=only_full_group_by.

But if I try to make a Template this happenes: Failed: Failed to insert template and I don't know the reason
