### ISSUE TITLE
ERROR STEAMGUARD

### ISSUE THREAD

**Issue by Wolfnight29** [devryan/GamePanelX-V3#177]
### I try create one new csgo template and i take that error

Redirecting stderr to '/home/Wolfnight29/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
[1mlogin sUSERNAME PASSWORD
[0m
Logging in user 'USERNAME' to Steam Public...
Enter the current code from your Steam Guard Mobile Authenticator app
Two-factor code:FAILED with result code 85
[1mquit
[0m

 i know the problem is steam guard but i dont have no idea howw fix that because steam guard change every time 

HELP ME!!!

**Comment by will2therich** [comment]
For most servers you do not need to own the game to download the server files.
Steam suggest making a second account and turning off steam guard you an then use this to login to steam with GamePanelX

**Comment by Wolfnight29** [comment]
tks itss fixed

**Comment by will2therich** [comment]
@Wolfnight29 
I'm glad!

**Comment by will2therich** [comment]
@devryan You can close this :P
