### ISSUE TITLE
GamePanelX Installation error

### ISSUE THREAD

**Issue by cailir** [devryan/GamePanelX-V3#182]
When I try to install GamePanelX it says:

> Error: You do not have MySQL support (mysql_connect) built into PHP! Rebuild your PHP install with MySQL support and try again.

But I have Mysql PHP installed on my ubuntu!

**Comment by MrRSEV** [comment]
you should install php-curl:

- apt-get update
- apt-get upgrade
- apt-get install php-curl
- service apache2 restart

**Comment by will2therich1** [comment]
Hi @cailir 

Are you using PHP7?
GPX doesn't currently support this see pr #181

**Comment by cailir** [comment]
Yes, I`m using PHP7

**Comment by will2therich** [comment]
Hi @cailir 
Please try my PHP7.0 branch
https://github.com/will2therich/GamePanelX-V3/tree/PHP7.0

Ta

**Comment by will2therich** [comment]
Hi @cailir 

Have you had any luck with the php7 branch?

**Comment by will2therich** [comment]
@devryan This can probs be closed

**Comment by mmasko** [comment]
> Hi @cailir
> 
> Have you had any luck with the php7 branch?

Will, just letting you know, I am working with your php7 branch, and I still get the PHP error mentioned here. I did install php-curl as suggested and restarted apache.
![image](https://user-images.githubusercontent.com/5659876/51431275-78346c00-1bdb-11e9-8f55-6dde8600dfe4.png)

**Comment by mmasko** [comment]
> Hi @cailir
> 
> Have you had any luck with the php7 branch?

Everything I have found points to mysql_connect being removed from PHP version 7 and replaced with mysqli_connect().

**Comment by alextwothousand** [comment]
> @devryan This can probs be closed

Hi there, I used your branch, however, when logging in it doesn't redirect me to the actual panel. I redirects me BACK to the homepage. Any fix for this?
