### ISSUE TITLE
Duplicate Entry

### ISSUE THREAD

**Issue by WTFBlaze** [devryan/GamePanelX-V3#186]
so I'm on the installation page of GamePanelX and i put all my info in and i get this as my response 

Error: Failed to run SQL: Duplicate entry '1' for key 'PRIMARY'

i don't know what to do.

**Comment by will2therich** [comment]
@dueckers5 

Hm Looks like there are two instances of something within (most likley a user)
And when the panel is trying to create another one its failing since its a primary key.

Try dropping the entire DB and recreating and trying again.
If not I can help and have a look into your DB to see what it is?

Ta

**Comment by WTFBlaze** [comment]
yeah if u have discord that would be extremely helpful as i tried doing what you said. and now it is telling me last_updated (which is under configuration) has no default. i go to the structure and it says none of the tables have defaults. Idk what to do at this point

**Comment by will2therich** [comment]
@dueckers5 

Yeah I have discord, give me a message (will2therich #3411) or join the GamePanelX Discord https://discord.gg/mg5sRC

**Comment by WTFBlaze** [comment]
Hey can u make another permanent invite link as it expired also that duscord taf dosent work

**Comment by will2therich** [comment]
Hi @dueckers5 

My bad.
New link!
https://discord.gg/MW5q5cM

**Comment by will2therich** [comment]
Issue seems to be caused by 'PHP 7.0.27'
Recommended to try installing using the following branch:
https://github.com/will2therich/GamePanelX-V3/tree/PHP7.0


@devryan This can be closed now :)
