### ISSUE TITLE
PHP5.6 error

### ISSUE THREAD

**Issue by cailir** [devryan/GamePanelX-V3#190]
When I try to install the panel it says:

> Error: You do not have MySQL support (mysql_connect) built into PHP! Rebuild your PHP install with MySQL support and try again.

I'm using php 5.6, Ubuntu 14.4.

**Comment by will2therich** [comment]
Hi @cailir 
Please try this branch.
https://github.com/will2therich/GamePanelX-V3/tree/PHP7.0

**Comment by cailir** [comment]
Thanks, now it's saying 
>Failed to select the database! Check your settings and try again.

**Comment by cailir** [comment]
Miss configuration... You can close this issue
