### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by SneaKz123** [devryan/GamePanelX-V3#202]
Hey Guys does anybody know how to fix this?

Also here is my log file:

[Tue Oct 27 23:08:18.031965 2020] [php7:error] [pid 19676] [client 93.202.151.28:60998] PHP Fatal error:  Uncaught Error: Call to a member function fetch_row() on bool in /var/www/html/mcweb/install/update.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/html/mcweb/install/update.php on line 20
[Tue Oct 27 23:08:20.680497 2020] [php7:error] [pid 19496] [client 93.202.151.28:60999] PHP Fatal error:  Uncaught Error: Call to a member function fetch_row() on bool in /var/www/html/mcweb/install/update.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/html/mcweb/install/update.php on line 20
[Tue Oct 27 23:08:43.882636 2020] [php7:error] [pid 19842] [client 93.202.151.28:61011] PHP Fatal error:  Uncaught Error: Call to a member function fetch_row() on bool in /var/www/html/mcweb/install/update.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/html/mcweb/install/update.php on line 20
[Tue Oct 27 23:09:20.960836 2020] [php7:error] [pid 19845] [client 93.202.151.28:61014] PHP Fatal error:  Uncaught Error: Call to a member function fetch_row() on bool in /var/www/html/mcweb/install/update.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/html/mcweb/install/update.php on line 20
[Tue Oct 27 23:09:49.170798 2020] [php7:error] [pid 19496] [client 93.202.151.28:61022] PHP Fatal error:  Uncaught Error: Call to a member function fetch_row() on bool in /var/www/html/mcweb/install/update.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/html/mcweb/install/update.php on line 20
[Wed Oct 28 07:57:39.312183 2020] [php7:error] [pid 19843] [client 49.232.11.17:53462] script '/var/www/html/elrekt.php' not found or unable to stat
[Wed Oct 28 07:57:41.032559 2020] [php7:error] [pid 19844] [client 49.232.11.17:56112] script '/var/www/html/index.php' not found or unable to stat
[Wed Oct 28 16:32:33.561998 2020] [php7:error] [pid 19495] [client 93.202.150.212:61577] PHP Fatal error:  Uncaught Error: Call to a member function fetch_row() on bool in /var/www/html/mcweb/install/update.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/html/mcweb/install/update.php on line 20
[Wed Oct 28 16:34:15.926124 2020] [mpm_prefork:notice] [pid 19489] AH00169: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20180731/mysqli (/usr/lib/php/20180731/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/mysqli.so (/usr/lib/php/20180731/mysqli.so: undefined symbol: mysqlnd_global_stats)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/mysql' (tried: /root/mysql (/root/mysql: cannot read file data: Is a directory), /usr/lib/php/20180731//root/mysql.so (/usr/lib/php/20180731//root/mysql.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
[Wed Oct 28 16:34:16.257939 2020] [mpm_prefork:notice] [pid 2417] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Wed Oct 28 16:34:16.258606 2020] [core:notice] [pid 2417] AH00094: Command line: '/usr/sbin/apache2'
[Wed Oct 28 16:34:25.298560 2020] [php7:error] [pid 2435] [client 93.202.150.212:61624] PHP Fatal error:  Uncaught Error: Call to a member function fetch_row() on bool in /var/www/html/mcweb/install/update.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/html/mcweb/install/update.php on line 20
[Wed Oct 28 16:35:34.025483 2020] [php7:error] [pid 2438] [client 93.202.150.212:61641] PHP Fatal error:  Uncaught Error: Call to a member function fetch_row() on bool in /var/www/html/mcweb/install/update.php:20\nStack trace:\n#0 {main}\n  thrown in /var/www/html/mcweb/install/update.php on line 20

**Comment by ethsmith** [comment]
Just use Pterodactyl. This is abandoned

**Comment by SneaKz123** [comment]
> Just use Pterodactyl. This is abandoned

Thanks for your answer.

ive decided to use the interface from teklab.
