### ISSUE TITLE
Counter Strike Global Offensive start issue

### ISSUE THREAD

**Issue by zekkozable** [devryan/GamePanelX-V3#75]
#CGameEventManager::AddListener: event 'round_end' unknown.
#CGameEventManager::AddListener: event 'difficulty_changed' unknown.
#GameTypes: initializing game types interface from GameModes.txt.
#GameTypes: merging game types interface from gamemodes_server.txt.
#KeyValues Error: LoadFromBuffer: missing { in file gamemodes_server.txt
#
#GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
Server is hibernating
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Stea
m, or a local steamclient.dll.
szCmd: /bin/sh -c '"/var/www/html/games//_SERVERS/.steam/root/steam.sh" steam://
run/215 -debug -game csgo -console -usercon -secure -maxplayers_override 10 +sv_
pure 0 +hostport 27015 +ip 31.220.27.139 +net_public_adr 31.220.27.139 +game_typ
e 0 +game_mode 0 +map de_dust2' &
serverGameDLL->DLLInit() failed.
/bin/sh: /var/www/html/games//_SERVERS/.steam/root/steam.sh: No such file or dir
ectory
./srcds_run: line 318: 1535 Segmentation fault $HL_CMD
cat: hlds.29635.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Wed Feb 5 14:12:53 EST 2014: Server restart in 10 seconds

**Comment by devryan** [comment]
This has been fixed, it should be related to the other steam issues - see latest commits on master branch of master+remote.  https://github.com/devryan/GamePanelX-V3/commit/29554eb7ed86c81e7fb4a919d4f37ebf5b39c27f
